# some more aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias hs='history -c'
alias cl='clear'
alias tp='top -U park'
alias n2='ssh park@nbody2'
alias n3='ssh park@nbody3'
alias n4='ssh park@nbody4'
alias sn2='sftp park@nbody2'
alias sn3='sftp park@nbody3'
alias sn4='sftp park@nbody4'
